version: "3"

volumes:
    gitea:

services:
    server:
        image: francium/gitea:latest
        restart: always
        ports:
            - "3000:3000"
            - "2222:2222"
        volumes:
            - gitea:/gitea
            - ./mount:/mount
