version: "3"

volumes:
    gitea:

networks:
    gitea:
        external: false

services:
    server:
        image: gitea:homebrew-1.4.1
        environment:
            - USER_UID=1000
            - USER_GID=1000
        restart: always
        networks:
            - gitea
        volumes:
            - gitea:/data
        ports:
            - "3000:3000"
            - "222:22"
